'use strict'
const assert=require('assert'),fs=require('fs'),path=require('path'),s=require('../lib/statement-ingestion'),root=path.join(__dirname,'..')
const migration=fs.readFileSync(path.join(root,'supabase/migrations/20260829000002_large_statement_ingestion_v1.sql'),'utf8'),api=fs.readFileSync(path.join(root,'api/statement-ingestion.js'),'utf8'),worker=fs.readFileSync(path.join(root,'api/admin/run-ingestion-worker.js'),'utf8'),ui=fs.readFileSync(path.join(root,'royalty-statements.html'),'utf8')
for(const t of ['statement_packages_v1','upload_sessions_v1','source_files_v1','ingestion_jobs_v1','processing_checkpoints_v1','import_chunks_v1','raw_source_rows_v1','adapter_versions_v1','column_mappings_v1','import_exceptions_v1','import_approvals_v1','processing_metrics_v1','dead_letter_jobs_v1'])assert(migration.includes(`royalty_intelligence.${t}`),`missing ${t}`)
assert(migration.includes('FOR UPDATE SKIP LOCKED'));assert(migration.includes('raw statement evidence is append-only'));assert(migration.includes('ENABLE ROW LEVEL SECURITY'));assert(migration.includes('statement_tus_insert_v1'))
assert(api.includes('5*1024*1024*1024'));assert(api.includes("malware_status!=='CLEAN'"));assert(api.includes("expected_royalty_handoff:'READY_FOR_EXPLICIT_CALCULATION_REQUEST'"));assert(!api.includes('external_action_enabled:true'))
assert(worker.includes('ROW_LIMIT'));assert(worker.includes('UNAVAILABLE_REVIEW_REQUIRED'));assert(worker.includes('MALWARE_SCAN_ATTESTATION_REQUIRED'));assert(worker.includes('DEAD_LETTER'))
assert(ui.includes('tus.Upload'));assert(/not money owed/i.test(ui));assert(/not independently verified/i.test(ui));assert(/projected.not certified/i.test(ui))
assert.deepStrictEqual(s.classify('bad.csv',Buffer.from('MZ...')),{format_key:'EXECUTABLE',supported:false,blocked:true,reason:'DOS/Windows executable signature'})
assert.strictEqual(s.detectDelimiter('a\tb\tc\n1\t2\t3'),'\t');assert.deepStrictEqual(s.normalizeHeader(['Net Royalty','Net Royalty','']),['net_royalty','net_royalty_2','column_3'])
assert.strictEqual(s.parseExactDecimal('$1,234.56'),'123456');assert.strictEqual(s.parseExactDecimal('-1.25'),'-125');assert.throws(()=>s.parseExactDecimal('1.234'),/PRECISION/)
async function parse(){const csv='title,amount,notes\n"A, B",1.00,"said ""yes"""\nZero,0.00,ok\n',slices=[csv.slice(0,17),csv.slice(17,35),csv.slice(35)],stream=new ReadableStream({start(c){for(const x of slices)c.enqueue(new TextEncoder().encode(x));c.close()}}),rows=[];for await(const r of s.parseDelimited(stream,{delimiter:','}))rows.push(r);assert.strictEqual(rows.length,3);assert.deepStrictEqual(rows[1].values,['A, B','1.00','said "yes"']);assert.strictEqual(rows[2].values[1],'0.00')}
parse().then(()=>console.log('large statement ingestion: schema, resumability, quarantine, parser, precision and UX controls passed'))
