'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const engine = require('../lib/registration-submission-engine');
const tracks = [{ id: 'track-1', track_title: 'Ready Work' }];
const ready = [{ catalog_track_id: 'track-1', destination: 'ASCAP', decision: 'READY', blockers: [] }];
const auth = { approved: true, reference: 'LOA-2026-001' };
const plan = engine.buildPlan({ destination: 'ASCAP', catalogId: 'catalog-1', tracks, readinessResults: ready, authorization: auth, requestedBy: 'user-1' });
assert.equal(plan.status, 'READY_FOR_REVIEW'); assert.equal(plan.summary.ready, 1); assert.equal(plan.external_submission_performed, false); assert.match(plan.payload_sha256, /^[a-f0-9]{64}$/);
const unevaluated = engine.buildPlan({ destination: 'ASCAP', catalogId: 'catalog-1', tracks, readinessResults: [], authorization: auth, requestedBy: 'user-1' });
assert.equal(unevaluated.status, 'BLOCKED'); assert.equal(unevaluated.items[0].blockers[0].code, 'READINESS_NOT_EVALUATED');
const blocked = engine.buildPlan({ destination: 'SOUNDEXCHANGE', catalogId: 'catalog-1', tracks, readinessResults: [], authorization: auth, requestedBy: 'user-1' });
assert.equal(blocked.status, 'BLOCKED');
const pending = engine.buildPlan({ destination: 'PPL', catalogId: 'catalog-1', tracks, readinessResults: [{ catalog_track_id: 'track-1', destination: 'NEIGHBORING_RIGHTS', decision: 'READY', blockers: [] }], authorization: auth, requestedBy: 'user-1' });
const pendingApproved = engine.approve(pending, { id: 'admin-1', role: 'registration_admin' }, 'Evidence and authorization reviewed.');
assert.throws(() => engine.dispatch(pendingApproved, { verified: true, destination: 'PPL', channel: 'PARTNER_PENDING' }), /unavailable/);
const approved = engine.approve(plan, { id: 'admin-1', role: 'registration_admin' }, 'Evidence and authorization reviewed.');
assert.equal(approved.status, 'APPROVED'); assert.throws(() => engine.dispatch(approved, { verified: false }), /Verified/);
const dispatching = engine.dispatch(approved, { verified: true, destination: 'ASCAP', channel: 'PORTAL_FILE' });
assert.equal(dispatching.external_submission_performed, false);
const submitted = engine.recordReceipt(dispatching, { external_reference: 'ASCAP-RECEIPT-1', received_at: new Date().toISOString() });
assert.equal(submitted.status, 'SUBMITTED'); assert.equal(submitted.external_submission_performed, true);
assert.throws(() => engine.approve(plan, { id: 'x', role: 'analyst' }, 'Evidence and authorization reviewed.'), /administrator/);
assert.throws(() => engine.transition('DRAFT', 'SUBMITTED'), /Invalid/);
assert.equal(Object.keys(engine.DESTINATIONS).length, 11);
const migration = fs.readFileSync(path.join(__dirname, '../supabase/migrations/20260907000000_registration_submission_engine_v1.sql'), 'utf8');
assert(migration.includes('registrations.registration_submission_packages_v1'));
assert(migration.includes("status IN('UNVERIFIED','TESTED','VERIFIED','SUSPENDED','RETIRED')"));
assert(migration.includes('events are append-only'));
assert(migration.includes('REVOKE ALL ON registrations.registration_submission_connectors_v1'));
console.log('registration submission engine: routing, authorization, approval, connector, receipt and fail-closed controls passed');
