'use strict'

const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8')
const register = fs.readFileSync(path.join(root, 'register.html'), 'utf8')
const success = fs.readFileSync(path.join(root, 'success.html'), 'utf8')
const verifyApi = fs.readFileSync(path.join(root, 'api/verify-checkout-session.js'), 'utf8')
const vercel = JSON.parse(fs.readFileSync(path.join(root, 'vercel.json'), 'utf8'))

assert(index.includes('href="/register?plan=starter"'))
assert(index.includes('href="/register?plan=growth"'))
assert(index.includes('href="/register?plan=pro"'))
assert(index.includes('href="/register?plan=label"'))
assert(register.includes("['starter', 'growth', 'pro', 'label'].includes(requestedPlan)"))
assert(register.includes('id="plan-pro"'))
assert(register.includes('id="plan-label"'))
assert(verifyApi.includes("session.metadata?.artist_id === artistId"))
const checkoutApi = fs.readFileSync(path.join(root, 'api/create-checkout-session.js'), 'utf8')
assert(checkoutApi.includes('STRIPE_PRO_PRICE_ID'))
assert(checkoutApi.includes('STRIPE_LABEL_PRICE_ID'))
assert(vercel.rewrites.some(route => route.source === '/pricing' && route.destination === '/index.html'))
assert(vercel.rewrites.some(route => route.source === '/register' && route.destination === '/register.html'))
assert(success.includes("'/api/verify-checkout-session'"))
assert(success.includes("'/api/verify-paypal-subscription'"))
assert(success.includes('portalLink.hidden = false'))
assert(verifyApi.includes("session.mode === 'subscription'"))
assert(verifyApi.includes("session.status === 'complete'"))
assert(verifyApi.includes("session.payment_status === 'paid'"))
assert(index.includes('MusiGod does not offer banking, custody, or investment services'))

console.log('revenue onboarding: pricing routes, plan carry-forward, Stripe verification and non-custodial copy passed')
