'use strict'
const assert=require('assert'),fs=require('fs'),path=require('path'),ExcelJS=require('exceljs'),yazl=require('yazl'),workers=require('../lib/specialized-statement-workers')
const root=path.join(__dirname,'..'),migration=fs.readFileSync(path.join(root,'supabase/migrations/20260830000000_specialized_statement_workers_v1.sql'),'utf8'),api=fs.readFileSync(path.join(root,'api/statement-ingestion.js'),'utf8'),runner=fs.readFileSync(path.join(root,'api/admin/run-ingestion-worker.js'),'utf8')
for(const table of ['source_file_members_v1','extracted_source_units_v1'])assert(migration.includes(`royalty_intelligence.${table}`));for(const adapter of ['generic_xlsx','generic_pdf_text','generic_zip'])assert(migration.includes(`'${adapter}'`));assert(migration.includes('ENABLE ROW LEVEL SECURITY'));assert(migration.includes('append-only'))
for(const job of ['STREAM_XLSX','EXTRACT_PDF','EXPAND_ZIP']){assert(api.includes(job));assert(runner.includes(job))}assert(runner.includes('OCR_REQUIRED'));assert(runner.includes('ARCHIVE_MEMBERS_REQUIRE_REVIEW'));assert(runner.includes('DEDICATED_WORKER_REQUIRED'))
assert(workers.safeArchivePath('statements/2026.csv'));assert(!workers.safeArchivePath('../secret.csv'));assert(!workers.safeArchivePath('/absolute.csv'));assert(workers.prohibitedMember('payload.exe'));assert.strictEqual(workers.memberFormat('royalties.xlsx'),'XLSX')
async function xlsx(){const book=new ExcelJS.Workbook(),a=book.addWorksheet('US'),b=book.addWorksheet('International');a.addRow(['Title','Net Royalty','Formula']);a.addRow(['Tha Regime','12.34',{formula:'1+1',result:2}]);b.addRow(['Title','Currency']);b.addRow(['Tha Regime','EUR']);const buffer=Buffer.from(await book.xlsx.writeBuffer()),stream=new ReadableStream({start(c){c.enqueue(buffer);c.close()}}),rows=[];for await(const row of workers.parseXlsx(stream))rows.push(row);assert.strictEqual(rows.length,2);assert.deepStrictEqual(rows.map(x=>x.worksheet_name),['US','International']);assert.strictEqual(rows[0].row_payload.net_royalty,'12.34');assert.strictEqual(rows[0].row_payload.formula,'2');assert.match(rows[1].source_location,/worksheet:International:row:2/);return buffer}
function zipBuffer(entries){return new Promise((resolve,reject)=>{const zip=new yazl.ZipFile(),chunks=[];for(const [name,data]of entries)zip.addBuffer(Buffer.from(data),name);zip.outputStream.on('data',x=>chunks.push(x)).on('end',()=>resolve(Buffer.concat(chunks))).on('error',reject);zip.end()})}
async function zip(){const buffer=await zipBuffer([['statement.csv','title,amount\nTha Regime,12.34\n'],['notes/readme.txt','Synthetic only']]),result=await workers.inspectZip(buffer);assert.strictEqual(result.members.length,2);assert.strictEqual(result.members[0].sha256.length,64);assert.strictEqual(workers.memberFormat(result.members[0].member_path),'CSV');const traversal=await zipBuffer([['safe.csv','x\n1']]);const ok=await workers.inspectZip(traversal,{includeData:false});assert.strictEqual(ok.members[0].data,undefined)}
function pdf(){const objects=['1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj','2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj','3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj','4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj','5 0 obj\n<< /Length 51 >>\nstream\nBT /F1 12 Tf 72 720 Td (Tha Regime 12.34 USD) Tj ET\nendstream\nendobj'];let out='%PDF-1.4\n',offsets=[0];for(const obj of objects){offsets.push(Buffer.byteLength(out));out+=obj+'\n'}const xref=Buffer.byteLength(out);out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(out)}
async function pdfTest(){const result=await workers.extractPdf(pdf());assert.strictEqual(result.page_count,1);assert.strictEqual(result.ocr_required,false);assert(result.pages[0].rows[0].values.join(' ').includes('Tha Regime'));const grouped=workers.groupPdfRows([{text:'A',x:10,y:100,width:1,height:1},{text:'B',x:20,y:101,width:1,height:1},{text:'C',x:10,y:80,width:1,height:1}]);assert.strictEqual(grouped.length,2);assert.deepStrictEqual(grouped[0].values,['A','B'])}
Promise.all([xlsx(),zip(),pdfTest()]).then(()=>console.log('specialized statement workers: XLSX streaming, PDF provenance, ZIP security and controls passed'))
